[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:airflow-webserver]
command=airflow webserver -p 8080
directory=/opt/airflow
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:airflow-scheduler]
command=airflow scheduler
directory=/opt/airflow
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:next-dashboard]
command=npm run start -- -p 3000
directory=/opt/pacewise/pacewise-frontend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

